# Generated by Django 5.2.6 on 2025-09-09 12:24

import authentification.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentification.models.CustomUserManager()),
            ],
        ),
    ]
