# Generated by Django 5.2.6 on 2025-09-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
