# Generated by Django 5.2.6 on 2025-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CLIENT', 'Client')], default='CLIENT', max_length=20),
        ),
    ]
