# Generated by Django 5.2.6 on 2025-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
