# Generated by Django 5.2.6 on 2025-09-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='signed_date',
            new_name='signed_at',
        ),
    ]
