# Generated by Django 5.2.6 on 2025-10-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_managerinvite'),
        ('contract', '0002_rename_signed_date_contract_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.company'),
            preserve_default=False,
        ),
    ]
