# Generated by Django 5.2.6 on 2025-10-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_managerinvite'),
        ('contract', '0005_alter_contract_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.company'),
        ),
    ]
