# Generated by Django 5.2.6 on 2025-10-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='company',
        ),
    ]
