# Generated by Django 5.2.6 on 2025-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contract_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
