# Generated by Django 5.2.6 on 2025-10-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
