# Generated by Django 5.2.6 on 2025-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
