# Generated by Django 5.2.6 on 2025-09-16 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(related_name='companies_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ManyToManyField(related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
