# Generated by Django 5.2.6 on 2025-09-16 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_clients_alter_company_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='manager',
            new_name='managers',
        ),
        migrations.AlterField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(null=True, related_name='companies_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(related_name='companies_categories', to='company.insurancecategory'),
        ),
    ]
