# Generated by Django 5.2.6 on 2025-09-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_insurancecategory_rename_manager_company_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecategory',
            name='parent',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='company.insurancecategory'),
            preserve_default=False,
        ),
    ]
