# Generated by Django 5.2.6 on 2025-09-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_insurancecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='company.insurancecategory'),
        ),
    ]
