# Generated by Django 5.2.6 on 2025-09-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_insurancecategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='managers',
        ),
    ]
