# Generated by Django 5.2.6 on 2025-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='clients',
        ),
    ]
