# Generated by Django 5.2.6 on 2025-10-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_managerinvite_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='description_original',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='name_original',
        ),
        migrations.AddField(
            model_name='company',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lang_original',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
