# Generated by Django 5.2.6 on 2025-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_managers'),
        ('insuranceproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='company.insurancecategory'),
        ),
    ]
